### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by sdfiuosueroeius** [jooy2/machini#1]
How to use this library in NextJS project?

I got error below when trying to use it:

```js
import { machineId } from 'machini';

export default function Home() {
  useEffect(() => {

    const getMachini = async () => {
      const machini = await machineId();
      console.log("machini", machini);
    };

    getMachini();
  }, []);

```
```
Import trace for requested module:
./app/page.tsx
 GET / 500 in 2143ms
 ⨯ ./node_modules/machini/dist/index.js:1:58
Module not found: Can't resolve 'child_process'
```

**Comment by jooy2** [comment]
Hello, Thank you for using machini.

This module is used on the server, not the client. It requires a backend environment where the NodeJS API is available.
Therefore, it is difficult to get the device ID of the client user; you will need to use another method, such as UUID, to achieve this.

Thank you.
